# Generated by Django 6.0.2 on 2026-03-24 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_patient_fee",
                    models.DecimalField(decimal_places=2, default=200.0, max_digits=8),
                ),
                (
                    "old_patient_fee",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
                ),
            ],
            options={
                "verbose_name_plural": "Fee Settings",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this to lock the client out of the system.",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Client Subscription Status",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_new_patient", models.BooleanField(default=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("09:00 AM", "09:00 AM"),
                            ("09:30 AM", "09:30 AM"),
                            ("10:00 AM", "10:00 AM"),
                            ("10:30 AM", "10:30 AM"),
                            ("11:00 AM", "11:00 AM"),
                            ("11:30 AM", "11:30 AM"),
                            ("12:00 PM", "12:00 PM"),
                            ("12:30 PM", "12:30 PM"),
                            ("02:00 PM", "02:00 PM"),
                            ("02:30 PM", "02:30 PM"),
                            ("03:00 PM", "03:00 PM"),
                            ("03:30 PM", "03:30 PM"),
                            ("04:00 PM", "04:00 PM"),
                            ("04:30 PM", "04:30 PM"),
                            ("05:00 PM", "05:00 PM"),
                            ("05:30 PM", "05:30 PM"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("fee_charged", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.patient",
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "time_slot")},
            },
        ),
    ]
