# Generated by Django 6.0.2 on 2026-04-10 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="height_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Height in cm",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="medicine_given",
            field=models.TextField(
                blank=True, default="", help_text="Medicine prescribed or given"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="symptoms",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Problem / Symptoms described by patient",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Weight in kg",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="appointments.patient",
            ),
        ),
    ]
