# Generated by Django 6.0.2 on 2026-04-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0002_appointment_height_cm_appointment_medicine_given_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
