# Generated by Django 6.0.2 on 2026-04-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_alter_patient_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="medicine_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
