# Generated by Django 6.0.2 on 2026-04-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_appointment_medicine_price_patient_email_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together=set(),
        ),
    ]
